services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--providers.file.filename=/etc/traefik/tls.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/tls.yml:/etc/traefik/tls.yml:ro
    networks:
      - proxy

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    depends_on:
      - web
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`watchdemo.pro`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.services.front.loadbalancer.server.port=80"

  web:
    restart: on-failure
    build:
      context: ./web
    ports:
      - "8000:8000"
    command: poetry run fastapi run --port 8000 main.py
    volumes:
      - ./web:/app
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - proxy
      - internal

  mailer:
    restart: on-failure
    build:
      context: mail
    volumes:
      - ./mail:/app
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - watchdemo_db_data:/var/lib/postgresql/data
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - watchdemo_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  watchdemo_db_data:
    driver: local
  watchdemo_rabbitmq_data:
    driver: local

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge
    internal: true